# Generated by Django 5.0.6 on 2024-09-28 07:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_user_otp_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_otp',
            name='username',
            field=models.TextField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user_otp',
            name='gen_otp',
            field=models.IntegerField(),
        ),
    ]
